/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package electoralserver;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Yash1861991
 */
public class DocumentVerification extends javax.swing.JFrame{

    /**
     * Creates new form DocumentVerification
     */
    public boolean x=false,y=false,z=false,w=false,q=false,res=false;
    public DocumentVerification() {
        initComponents();
        documentverificationbuttonprevious.setEnabled(false);
        documentverificationbuttonnext.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        documentverificationbuttongo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        documentverificationbuttonconfirm = new javax.swing.JButton();
        documentverificationbuttondone = new javax.swing.JButton();
        documentverificationbuttonprevious = new javax.swing.JButton();
        documentverificationbuttonnext = new javax.swing.JButton();
        documentverificationbuttonexit = new javax.swing.JButton();
        documentverificationbuttonrejectrecord = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Document Verification");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter Voter ID  :");

        documentverificationbuttongo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        documentverificationbuttongo.setText("GO");
        documentverificationbuttongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentverificationbuttongoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("               Name :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("F/ H/ M    Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("         Age :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("       Sex :");

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox1.setText("Age Proof");

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox2.setText("Address Proof");

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox3.setText("Form 6/ Form 8 submitted");

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox4.setText("Read photocopy of originals and verified with originals");

        jCheckBox5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBox5.setText("Photo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Birth Certificate", "College leaving certificate", "SSC marksheet", "Adhaar Card", "Driving Licence", "Pan Card", "Bank Passbook", " " }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Driving Licence", "Adhaar Card", "Ration Card", "employee Card", " " }));

        documentverificationbuttonconfirm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        documentverificationbuttonconfirm.setText("Confirm");
        documentverificationbuttonconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentverificationbuttonconfirmActionPerformed(evt);
            }
        });

        documentverificationbuttondone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        documentverificationbuttondone.setText("Done");
        documentverificationbuttondone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentverificationbuttondoneActionPerformed(evt);
            }
        });

        documentverificationbuttonprevious.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        documentverificationbuttonprevious.setText("Previous");
        documentverificationbuttonprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentverificationbuttonpreviousActionPerformed(evt);
            }
        });

        documentverificationbuttonnext.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        documentverificationbuttonnext.setText("Next");
        documentverificationbuttonnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentverificationbuttonnextActionPerformed(evt);
            }
        });

        documentverificationbuttonexit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        documentverificationbuttonexit.setText("Exit");
        documentverificationbuttonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentverificationbuttonexitActionPerformed(evt);
            }
        });

        documentverificationbuttonrejectrecord.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        documentverificationbuttonrejectrecord.setText("Reject Record");
        documentverificationbuttonrejectrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentverificationbuttonrejectrecordActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/electoralserver/index_12.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox1)
                                            .addComponent(jCheckBox2))
                                        .addGap(86, 86, 86)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, 0, 220, Short.MAX_VALUE)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(documentverificationbuttonprevious, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                            .addComponent(documentverificationbuttonconfirm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(documentverificationbuttondone, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(documentverificationbuttonnext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(documentverificationbuttonexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(documentverificationbuttonrejectrecord, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(documentverificationbuttongo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(documentverificationbuttongo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(8, 8, 8)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(documentverificationbuttonrejectrecord, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(documentverificationbuttondone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(documentverificationbuttonconfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentverificationbuttonexit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentverificationbuttonnext, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentverificationbuttonprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void documentverificationbuttondoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentverificationbuttondoneActionPerformed
        // TODO add your handling code here:
        
        Integer wardno = 0,voterid = 0,id;
        id=Integer.parseInt(jTextField1.getText());
        
        try {
           if(res)
           {
             MySqlConnection mysql= new MySqlConnection();
             Connection con = (Connection) mysql.getMySQLConnection();
             ResultSet rs1 = con.prepareStatement("select * from photoidentity where voterid ='"+id+"'").executeQuery();
             
             while(rs1.next())
             {
             wardno=rs1.getInt(3);
             voterid=rs1.getInt(4);
             }
             
            String query="INSERT INTO verificationofficer(voterid,wardno)VALUES('"+voterid+"','"+wardno+"') ";
            System.out.println(query);
            PreparedStatement stmt = con.prepareStatement(query);
            stmt.executeUpdate();
           }
           else
           {
                 JOptionPane.showMessageDialog(null,"Please... Confirm Document verification  first...", "OK",JOptionPane.INFORMATION_MESSAGE);            
           }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_documentverificationbuttondoneActionPerformed

    private void documentverificationbuttongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentverificationbuttongoActionPerformed
        // TODO add your handling code here:
        
        String votername = null,votersurname = null,vfhm = null,vsex = null;
        Integer voterid, vage = 0,vward,id;
        
             voterid=Integer.parseInt(jTextField1.getText());
             
        try {
              MySqlConnection mysql= new MySqlConnection();
             Connection con = (Connection) mysql.getMySQLConnection();
             //ResultSet rs = con.prepareStatement("select * from voter").executeQuery();
             ResultSet rs = con.prepareStatement("select * from modification where voterid ='"+voterid+"'").executeQuery();
             
             while(rs.next())
             {
                 id=rs.getInt(1);
                 
                 if(id==voterid)
                 {
                     votername=rs.getString(2);
                     votersurname=rs.getString(4);
                     vfhm=rs.getString(3);
                     vage=rs.getInt(7);
                     vsex=rs.getString(5);
                     
                 }
             }
         
             jTextField2.setText(votername);
             jTextField3.setText(votersurname);
             jTextField4.setText(vfhm);
             jTextField5.setText(""+vage);
             jTextField6.setText(vsex);
         } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_documentverificationbuttongoActionPerformed

    private void documentverificationbuttonconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentverificationbuttonconfirmActionPerformed
        
        //modification table
        Integer wardno,voterid,id;
        
        //photoidentity table
        Integer wardnumber,voteridnumber;
       
        id=Integer.parseInt(jTextField1.getText());
        x=jCheckBox1.isSelected();
        y=jCheckBox2.isSelected();
        z=jCheckBox3.isSelected();
        w=jCheckBox4.isSelected();
        q=jCheckBox5.isSelected();
       
        try {
             MySqlConnection mysql= new MySqlConnection();
             Connection con = (Connection) mysql.getMySQLConnection();
             Connection con1 = (Connection) mysql.getMySQLConnection();
             ResultSet rs = con.prepareStatement("select * from modification where voterid ='"+id+"'").executeQuery();
             ResultSet rs1 = con1.prepareStatement("select * from photoidentity where voterid ='"+id+"'").executeQuery();
             
             while(rs.next() && rs1.next() )
             {
                 voterid=rs.getInt(1);
                 wardno=rs.getInt(15);
                
                 wardnumber=rs1.getInt(3);
                 voteridnumber=rs1.getInt(4);
                
                 if(voterid==voteridnumber && wardno==wardnumber)
                 {
                      res=x && y && z && w && q;
                 }
               }
         
          } catch (Exception e) {
            e.printStackTrace();
        }
       
        if(res)
        {    
        JOptionPane.showMessageDialog(null,"Confirm Document verification...", "OK",JOptionPane.INFORMATION_MESSAGE);   
        documentverificationbuttonprevious.setEnabled(true);
        documentverificationbuttonnext.setEnabled(true);
        
        }
        else
        {
        JOptionPane.showMessageDialog(null,"Verification not validated ", "OK",JOptionPane.INFORMATION_MESSAGE);             
        }
        
    }//GEN-LAST:event_documentverificationbuttonconfirmActionPerformed

    private void documentverificationbuttonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentverificationbuttonexitActionPerformed
        // TODO add your handling code here:
        verificationofficer v =new verificationofficer();
        v.show();
        this.dispose();
    }//GEN-LAST:event_documentverificationbuttonexitActionPerformed

    private void documentverificationbuttonrejectrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentverificationbuttonrejectrecordActionPerformed
        // TODO add your handling code here:
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        
        documentverificationbuttonprevious.setEnabled(false);
        documentverificationbuttonnext.setEnabled(false);

    }//GEN-LAST:event_documentverificationbuttonrejectrecordActionPerformed

    private void documentverificationbuttonpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentverificationbuttonpreviousActionPerformed
        // TODO add your handling code here:
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        
        DocumentVerification v =new DocumentVerification();
        v.show();
        this.dispose();

    }//GEN-LAST:event_documentverificationbuttonpreviousActionPerformed

    private void documentverificationbuttonnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentverificationbuttonnextActionPerformed
        // TODO add your handling code here:
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        
        DocumentVerification v =new DocumentVerification();
        v.show();
        this.dispose();

        
    }//GEN-LAST:event_documentverificationbuttonnextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocumentVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocumentVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocumentVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocumentVerification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocumentVerification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton documentverificationbuttonconfirm;
    private javax.swing.JButton documentverificationbuttondone;
    private javax.swing.JButton documentverificationbuttonexit;
    private javax.swing.JButton documentverificationbuttongo;
    private javax.swing.JButton documentverificationbuttonnext;
    private javax.swing.JButton documentverificationbuttonprevious;
    private javax.swing.JButton documentverificationbuttonrejectrecord;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
